# Generated by Django 2.1 on 2018-04-21 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist_manager', '0003_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.CharField(help_text='Enter a Search String', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='shared_status',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='owner',
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
